<a href="https://colab.research.google.com/github/RMoulla/pyk/blob/main/Tuto_python_numpy_fonctions_regex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tuto NumPy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [ ]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a * 2)
print(b / a)
print(a ** 2)

[11 22 33]
[2 4 6]
[10. 10. 10.]
[1 4 9]


In [ ]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[1:4])

10
[20 30 40]


In [ ]:
a = np.array([1, 2, 3, 4])
print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a), np.max(a))

10
2.5
1.118033988749895
1 4


In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a.shape)
print(a.ndim)
print(a.reshape(4, 1))
print(a.flatten())

(2, 2)
2
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a + b)

[[11 22]
 [13 24]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a[a > 3])


[4 5]


# Tuto Fonctions Python

In [ ]:
def saluer():
    print("Bonjour !")
saluer()

Bonjour !


In [ ]:
def saluer_nom(nom):
    print(f"Bonjour {nom} !")
saluer_nom("Tom")

Bonjour Tom !


In [ ]:
def carre(x):
    return x * x
carre(2)

4

In [ ]:
def saluer(nom="inconnu"):
    print(f"Salut {nom} !")

saluer()

In [ ]:
def addition(a, b):
    return a + b
print(addition(3, 7))

10


In [ ]:
def presentation(nom, age):
    print(f"{nom} a {age} ans.")
presentation(age=30, nom="Sarah")

Sarah a 30 ans.


# Tuto Traitement de texte avec RegEx

In [ ]:
import re

In [ ]:
text = """
Alice et Bob sont amis.
"""

match = re.search(r"Alice", text)

print(match.group())

Alice


In [ ]:
texte = "Voici mon email : exemple@test.com et mon site : www.test.fr"
email = re.search(r'\S+@\S+\.\S+', texte)
print(email.group())

exemple@test.com


In [ ]:
texte = "Bonjour à TOUS les MEMBRES de L'ASSEMBLÉE"
majuscules = re.findall(r'\b[A-ZÉÈÊÀ]+\b', texte)
print(majuscules)

['TOUS', 'MEMBRES', 'L', 'ASSEMBLÉE']


In [ ]:
texte = "Il y a 3 pommes, 25 bananes et 178 fraises."
nombres = re.findall(r'\d+', texte)
print(nombres)

['3', '25', '178']


In [ ]:
texte = "Jean-Paul;Luc,Marie|Sophie"
prenoms = re.split(r'[;,\|]', texte)
print(prenoms)

['Jean-Paul', 'Luc', 'Marie', 'Sophie']


In [ ]:
# Ordonner une liste de chaines de caractère par ordre alphabétique

liste_chaines = ["cerise", "banane", "pomme", "datte"]
liste_ordonnee = sorted(liste_chaines)
liste_ordonnee


['banane', 'cerise', 'datte', 'pomme']